//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
<<<<<<< HEAD
// Generated on: 2021.08.04 at 07:55:55 PM EEST 
=======
// Generated on: 2021.07.16 at 11:10:31 AM EEST 
>>>>>>> master
=======
// Generated on: 2021.08.05 at 09:25:24 AM EEST 
>>>>>>> 8116f86a08b0b693bf5902174d8737bafd9c3950
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.service.product.se.com/model/soap", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.se.product.service.model.soap;
